defmodule Din.Resources.Channel.Message do
  alias Din.Permissions.Role
  alias Din.Resources.{Channel, User}

  @typedoc "id of the message"
  @type id :: integer

  @typedoc "id of the channel the message was sent in"
  @type channel_id :: Channel.id

  @typedoc "the author of this message"
  @type author :: User.t

  @typedoc "contents of the message"
  @type content :: String.t

  @typedoc "when this message was sent"
  @type timestamp :: String.t

  @typedoc "when this message was edited (or null if never)"
  @type edited_timestamp :: String.t | nil

  @typedoc "whether this was a TTS message"
  @type tts :: boolean

  @typedoc "whether this message mentions everyone"
  @type mention_everyone :: boolean

  @typedoc "users specifically mentioned in the message"
  @type mentions :: list(User.t)

  @typedoc "roles specifically mentioned in this message"
  @type mention_roles :: list(Role.t)

  @typedoc "any attached files"
  @type attachments :: list(Channel.Attachment.t)

  @typedoc "any embedded content"
  @type embeds :: list(Channel.Embed.t)

  @typedoc "reactions to the message"
  @type reactions :: list(Channel.Reaction.t)

  @typedoc "used for validating a message was sent"
  @type nonce :: integer | nil

  @typedoc "whether this message is pinned"
  @type pinned :: boolean

  @typedoc "if the message is generated by a webhook, this is the webhook's id"
  @type webhook_id :: String.t

  @typedoc "type of message"
  @type type :: 0..7

  @enforce_keys [:id, :channel_id, :author, :content, :timestamp, :edited_timestamp, :tts, :mention_everyone, :mentions, :mention_roles, :attachments, :embeds, :pinned, :type]
  defstruct [:id, :channel_id, :author, :content, :timestamp, :edited_timestamp, :tts, :mention_everyone, :mentions, :mention_roles, :attachments, :embeds, :reactions, :nonce, :pinned, :webhook_id, :type]
  @type t :: %__MODULE__{
    id: id,
    channel_id: channel_id,
    author: author,
    content: content,
    timestamp: timestamp,
    edited_timestamp: edited_timestamp,
    tts: tts,
    mention_everyone: mention_everyone,
    mentions: mentions,
    mention_roles: mention_roles,
    attachments: attachments,
    embeds: embeds,
    pinned: pinned,
    type: type
  }
end
